### PR TITLE
revert changes

### LINKED ISSUE #120: Not working with webpack@5.46.0
```
webpack-webextension-plugin listens on ws://localhost:35729
[webpack-cli] TypeError: fileSystemInfo._fileTimestamps.entries is not a function
    at WebextensionPlugin.extractChangedFiles (***\node_modules\webpack-webextension-plugin\index.js:245:48)
    at WebextensionPlugin.reloadExtensions (***\node_modules\webpack-webextension-plugin\index.js:226:31)
    at WebextensionPlugin.done (***\node_modules\webpack-webextension-plugin\index.js:98:10)
    at Hook.eval [as callAsync] (eval at create (***\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (***\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (***\node_modules\webpack\lib\Watching.js:273:28)
    at ***\node_modules\webpack\lib\Watching.js:195:21
    at Compiler.emitRecords (***\node_modules\webpack\lib\Compiler.js:874:39)
    at ***\node_modules\webpack\lib\Watching.js:173:22
    at ***\node_modules\webpack\lib\Compiler.js:856:14
```

### PR DESCRIPTION
**Pull request by fchastanet**
/fixes #120 
I push a fix that I was not sure 2 months ago, so here the revert of my changes
retesting it today I see that your current master with my changes doesn't work with my current version of webpack.
I guess webpack has changed something since my last test.
sorry about that.

### CODE REVIEW

**Comment by desonov** [comment]
It doesn't work for me. webpack 5.64.2
```
 [webpack-cli] TypeError: Cannot read properties of undefined (reading 'entries')
     at WebextensionPlugin.extractChangedFiles (-----\webpack-webextension-plugin\index.js:246:57)
     at WebextensionPlugin.reloadExtensions (-----\webpack-webextension-plugin\index.js:226:31)
     at WebextensionPlugin.done (------\webpack-webextension-plugin\index.js:98:10)
```
I fixed the problem like this: #143

**Comment by tm1000** [comment]
Thanks @fchastanet superseded by @desonov
