### ISSUE TITLE
Not working with webpack@5.46.0

### ISSUE THREAD

**Issue by OpportunityLiu** [webextension-toolbox/webpack-webextension-plugin#120]
```
webpack-webextension-plugin listens on ws://localhost:35729
[webpack-cli] TypeError: fileSystemInfo._fileTimestamps.entries is not a function
    at WebextensionPlugin.extractChangedFiles (***\node_modules\webpack-webextension-plugin\index.js:245:48)
    at WebextensionPlugin.reloadExtensions (***\node_modules\webpack-webextension-plugin\index.js:226:31)
    at WebextensionPlugin.done (***\node_modules\webpack-webextension-plugin\index.js:98:10)
    at Hook.eval [as callAsync] (eval at create (***\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (***\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (***\node_modules\webpack\lib\Watching.js:273:28)
    at ***\node_modules\webpack\lib\Watching.js:195:21
    at Compiler.emitRecords (***\node_modules\webpack\lib\Compiler.js:874:39)
    at ***\node_modules\webpack\lib\Watching.js:173:22
    at ***\node_modules\webpack\lib\Compiler.js:856:14
```

**Comment by KnightYoshi** [comment]
Also running into this
